baseURL = "https://hello.branchwebpresence.com"
languageCode = "en-us"
title = "Web Presence for Local Businesses"
disableKinds = ["sitemap", "RSS"]
theme = "reveal"
themesDir = "themes"
tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  author = "Justin Langhorst"
  homepage = "https://www.branchwebpresence.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = false # use highlight.js, true uses highlighting at compile time
    style = "tango"

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[params.reveal_hugo]
  history = true
  [params.reveal_hugo.templates.grey]
    background = "#424242"
    transition = "convex"
